### ISSUE TITLE
OL9.3: cannot boot from ISO image (grub loopback)

### ISSUE THREAD

**Issue by Mexit** [oracle/oracle-linux#129]
Logs:
[rdsosreport.txt](https://github.com/oracle/oracle-linux/files/14649757/rdsosreport.txt)

Grub configuration:
```
iso_path="$2"
loopback loop $iso_path
probe --label --set=cd_label (loop)
isocfg="iso-scan/filename=$iso_path"
bootoptions="inst.stage2=hd:LABEL=$cd_label"
linux_path="(loop)/images/pxeboot/vmlinuz"
initrd_path="(loop)/images/pxeboot/initrd.img"

menuentry "Install Oracle Linux" {
	echo Loading kernel...
	linux $linux_path $isocfg $bootoptions quiet
	echo Loading initrd...
	initrd $initrd_path
}
```

**Comment by tvierling** [comment]
Thank you for the report; we'll look into it. This is likely the same reason the current ISOs aren't working with Ventoy.

I cannot guarantee a fast fix for this since we generally don't reissue ISOs once released. (Loopback booting is not a supported use case, but yes, we'd *like* to make this work again.)

Does the 9.2 ISO work for you? If so, you can start with that. For instance, the boot/uekboot ISO can be used with network yum repos to install latest RPMs, yielding an up-to-date OL9 system after install.

**Comment by Mexit** [comment]
OL9.x ISO on exfat partition Linux boots correctly. For me it is enough. Thanks
