### ISSUE TITLE
dnf-automatic fails when GPG key not installed

### ISSUE THREAD

**Issue by anandb-ripencc** [oracle/oracle-linux#132]
I'm reporting an issue about `dnf-automatic` version 4.14.0 on Oracle Linux 9.3.

When dnf-automatic is enabled for automatic updates, and a new repository is added to the system containing a URL to a GPG key, and `gpgcheck=1`, dnf-automatic fails to update the system. I would have expected it to run the equivalent of `dnf -y update`, but that doesn't appear to be the case.

**Comment by tvierling** [comment]
GPG key import is always a manual operation, because you don't want a rogue software source randomly installing updates. The key import specifically requires user confirmation.

Make sure, when setting up a new repo that requires a custom GPG key, to run `dnf update` at least once manually to install that key.
