### ISSUE TITLE
kernel-4.18.0-477.15.1.el8_8 packages are missing from Oracle public repos

### ISSUE THREAD

**Issue by iwbarker** [oracle/oracle-linux#94]
On 6/27/2023 Red Hat released kernel 4.18.0-477.15.1.el8_8 as an update for the TLS security fix CVE-2023-28466
https://access.redhat.com/errata/RHSA-2023:3847

On 7/3/2023 Oracle released a Ksplice update for RHCK 8 (ELSA-2023-3847) for the same fix, referencing ELSA-2023-3847
But ELSA-2023-3847 does not exist on the Oracle errata at https://linux.oracle.com/errata/ELSA-2023-3847.html

The corresponding OL binary and source code RPMs for 477.15.1 are also not present in the Oracle public repos:
https://yum.oracle.com/repo/OracleLinux/OL8/baseos/latest/x86_64/index.html
https://yum.oracle.com/repo/OracleLinux/OL8/baseos/latest/x86_64/index_src.html

i.e. Oracle Linux RHCK 8 in the public repos is now out of sync to Red Hat Linux 8 kernel by 3 weeks.

Note: this is the first kernel update subsequent to the change in RHEL upstream source publishing policy.

**Comment by iwbarker** [comment]
Same data posted on the Oracle open-source community forum:
https://forums.oracle.com/ords/apexds/post/kernel-4-18-0-477-15-1-el8-8-packages-are-missing-from-orac-0917

**Comment by tvierling** [comment]
It has taken a little time to ramp up new package maintenance procedures to deal with the recent Red Hat announcement. We shipped the Ksplice early to make sure the fix was available to customers as quickly as we could.

However, we do have these fixes in work and we will continue to release CVE fixes by RPM as normal. It's on the way.

[this response also at https://forums.oracle.com/ords/apexds/post/kernel-4-18-0-477-15-1-el8-8-packages-are-missing-from-orac-0917#comment_1141165820510911033052803758476105847]

**Comment by iwbarker** [comment]
thanks
